### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [cdodd/doodleshell-zsh-theme#1]
I was doing some cleanup of [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) and noticed this theme doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by cdodd** [comment]
MIT license added in commit e1efb2d

**Comment by unixorn** [comment]
TY
